include theos/makefiles/common.mk

BUNDLE_NAME = LowerInstallSettings
LowerInstallSettings_FILES = /mnt/d/codes/lowerinstall/lowerinstallsettings/LowerInstallSettingsController.mm
LowerInstallSettings_INSTALL_PATH = /Library/PreferenceBundles
LowerInstallSettings_FRAMEWORKS = UIKit QuartzCore CoreGraphics MessageUI Social Twitter
LowerInstallSettings_PRIVATE_FRAMEWORKS = Preferences
LowerInstallSettings_CFLAGS = -fobjc-arc
LowerInstallSettings_ARCHS = armv7 arm64
export ARCHS = armv7 arm64

include $(THEOS_MAKE_PATH)/bundle.mk

all::
